// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmakjbtwtnpvbbgoeoje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtYWtqYnR3dG5wdmJiZ29lb2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTAyNTEsImV4cCI6MjA2OTM4NjI1MX0.wxE1v6pZhPoz5EiqlDtGAqTWWHtc2-7RUxLSVRKCb_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});